### ISSUE TITLE
A disappointment

### ISSUE THREAD

**Issue by FranklinChen** [nescalas/proposals-2016#15]
Dear Editor:

Once again I am disappointed by the unwarranted and misleading change to the title of one of my letters. Perhaps you do not share my priorities, as the intellectual climate of our profession continues to degenerate, but please reinstate my original title, "A Case Against the Goto Statement".

prof. dr. Edsger W. Dijkstra

**Comment by SethTisue** [comment]
LOL

**Comment by MartinSnyder** [comment]
:)

**Comment by bmc** [comment]
Fixed. May the ghost of Prof. Dijkstra now cease waking us up at night. (I'm tired of hearing his complaints about the C programming language.)
