### ISSUE TITLE
How does the voting work?

### ISSUE THREAD

**Issue by sellout** [nescalas/proposals-2016#36]
I saw “there is a danger of splitting your votes” in the context of submitting multiple proposals, but there are many voting systems where splitting votes isn’t a concern. One of those might be more appropriate in this situation.

Approval voting seems like the simplest that would work here.

**Comment by bmc** [comment]
Our goals:
- **Simplicity.** Nothing overly complicated.
- **Variation.** We absolutely do not want the same speaker giving two talks on Day 1. So we disallow that.

If you have multiple talks, then vote splitting is possible. But if there's high interest in the _speaker_, then we (the organizers) may elect to make some kind of final determination.

**Comment by sellout** [comment]
So, I think Approval voting works well for this – each voter just separates the proposals into two groups (a checkbox for each proposal is fine) – ones they like, and ones they don’t like. They can split them 50/50, or put all-but-one into one of the buckets, or any other combination.

The results are ordered by number of “likes”. Then you can just walk down that ordered list, and once a speaker has been selected, you can reject any of their lower-scored talks. If someone has submitted three talks, a voter can indicate that they like one of the topics by voting for it, or can indicate that they’re interested in the speaker by voting for all of their talks (IE, no splitting).

Anyway, if you have an established system, I’m not trying to overturn it. Just a thought in light of that particular issue.

**Comment by sellout** [comment]
On second thought, I’m only submitting one proposal, so maybe I should keep my mouth shut about vote splitting! 😉

**Comment by bmc** [comment]
I'm not trying to disrespect your suggestion. But we tend to stick with what works, and our (less rigorous) approach has worked fine for five years. We're all about minimizing workload for us organizers. ;-)

**Comment by sellout** [comment]
👍🏽 Totally on board with that. Thanks.
